---
title: "Selling Price of Used Cars"
author: "Team-1"
date: "today"

# date: "`r Sys.Date()`"

output:
  html_document:
    code_folding: hide
    # number_sections: true
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r basic, include = F}
# use this function to conveniently load libraries and work smoothly with knitting
# can add quietly=T option to the require() function
# the loadPkg function essentially replaced/substituted two functions install.packages() and library() in one step.
loadPkg = function(x) { if (!require(x,character.only=T, quietly =T)) { install.packages(x,dep=T,repos="http://cran.us.r-project.org"); if(!require(x,character.only=T)) stop("Package not found") } }
# unload/detact package when done using it
unloadPkg = function(pkg, character.only = FALSE) { 
  if(!character.only) { pkg <- as.character(substitute(pkg)) } 
  search_item <- paste("package", pkg,sep = ":") 
  while(search_item %in% search()) { detach(search_item, unload = TRUE, character.only = TRUE) } 
}
```

```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
# knitr::opts_chunk$set(include = F)
# knitr::opts_chunk$set(echo = TRUE)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```
```{r xkablesummary}
loadPkg("xtable")
loadPkg("kableExtra")
loadPkg("stringi")
xkabledply = function(modelsmmrytable, title="Table", digits = 4, pos="left", bso="striped", wide=FALSE) { 
  #' Combining base::summary, xtable, and kableExtra, to easily display model summary. 
  #' wrapper for the base::summary function on model objects
  #' Can also use as head for better display
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param modelsmmrytable This can be a generic table, a model object such as lm(), or the summary of a model object summary(lm()) 
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @param wide print table in long (FALSE) format or wide (TRUE) format
  #' @return HTML table for display
  #' @examples
  #' library("xtable")
  #' library("kableExtra")
  #' xkabledply( df, title="Table testing", pos="left", bso="hover" )
  #' xkabledply( ISLR::Hitters[1:5,] )
  if (wide) { modelsmmrytable <- t(modelsmmrytable) }
  modelsmmrytable %>%
    xtable() %>% 
    kable(caption = title, digits = digits) %>%
    kable_styling(bootstrap_options = bso, full_width = FALSE, position = pos)
}
xkabledplyhead = function(df, rows=5, title="Head", digits = 4, pos="left", bso="striped") { 
  xkabledply(df[1:rows, ], title, digits, pos, bso, wide=FALSE)
}
xkabledplytail = function(df, rows=5, title="Tail", digits = 4, pos="left", bso="striped") { 
  trows = nrow(df)
  xkabledply(df[ (trows-rows+1) : trows, ], title, digits, pos, bso, wide=FALSE)
}
xkablesummary = function(df, title="Table: Statistics summary.", digits = 4, pos="left", bso="striped") { 
  #' Combining base::summary, xtable, and kableExtra, to easily display numeric variable summary of dataframes. 
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param df The dataframe.
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @return The HTML summary table for display, or for knitr to process into other formats 
  #' @examples
  #' xkablesummary( faraway::ozone )
  #' xkablesummary( ISLR::Hitters, title="Five number summary", pos="left", bso="hover"  )
  
  s = summary(df) %>%
    apply( 2, function(x) stringr::str_remove_all(x,c("Min.\\s*:\\s*","1st Qu.\\s*:\\s*","Median\\s*:\\s*","Mean\\s*:\\s*","3rd Qu.\\s*:\\s*","Max.\\s*:\\s*")) ) %>% # replace all leading words
    apply( 2, function(x) stringr::str_trim(x, "right")) # trim trailing spaces left
  
  colnames(s) <- stringr::str_trim(colnames(s))
  
  if ( dim(s)[1] ==6 ) { rownames(s) <- c('Min','Q1','Median','Mean','Q3','Max') 
  } else if ( dim(s)[1] ==7 ) { rownames(s) <- c('Min','Q1','Median','Mean','Q3','Max','NA') }
  
  xkabledply(s, title=title, digits = digits, pos=pos, bso=bso )
}
xkablevif = function(model, title="VIFs of the model", digits = 3, pos="left", bso="striped", wide=TRUE) { 
  #' Combining faraway::vif, xtable, and kableExtra, to easily display numeric summary of VIFs for a model. 
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param model The lm or compatible model object.
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @param wide print table in long (FALSE) format or wide (TRUE) format
  #' @return The HTML summary table of the VIFs for a model for display, or for knitr to process into other formats 
  #' @examples
  #' xkablevif( lm(Salary~Hits+RBI, data=ISLR::Hitters), wide=T )
  
  vifs = table( names(model$coefficients)[2:length(model$coefficients)] ) # remove intercept to set column names
  vifs[] = faraway::vif(model) # set the values
  if (wide) { vifs <- t(vifs) }
  xkabledply( vifs, title=title, digits = digits, pos=pos, bso=bso )
}
```
# R-Project2 - Used Cars Selling Price

```{r, results = 'markup'}
# Reading the Car dataset
vehicle <- read.csv("Car details v3.csv")
x <- capture.output(dput(names(vehicle)))

cat("The vehicle dataset consists of", nrow(vehicle), "observations with", ncol(vehicle), "variables. The variables are \n", x, "\n \n")
cat("Some variables are identified as categorical: Fuel, transmission and seller_type, and others are numerical. But the numerical variables consist of string suffixes (units) in their values. Also, some were blanks. So the data needed to be cleaned. \n")

# Removing the rows with blanks and unwanted values
vehicle <- vehicle[!((vehicle$mileage=="") | (vehicle$max_power==" bhp") |(vehicle$mileage == "0.0 kmpl")), ]

# Removing suffixes from the following columns
vehicle$mileage <- gsub("kmpl","", as.character(vehicle$mileage))
vehicle$mileage <- gsub("km/kg","", as.character(vehicle$mileage))
vehicle$engine <- gsub("CC","", as.character(vehicle$engine))
vehicle$max_power <- gsub("bhp","", as.character(vehicle$max_power))

vehicle$torque <- sub("N.*", "", vehicle$torque)
vehicle$torque <- sub("k.*", "", vehicle$torque)
vehicle$torque <- sub("n.*", "", vehicle$torque)
vehicle$torque <- sub("@.*", "", vehicle$torque)
vehicle$torque <- sub("K.*", "", vehicle$torque)

# Converting the following variables to factor
vehicle[c("fuel","transmission", "seller_type")] <- sapply(vehicle[c("fuel","transmission", "seller_type")],as.factor)

# Assigning labels to owner_type
vehicle$owner <- factor(vehicle$owner, labels = c(0,1,2,3,4), levels = c("Test Drive Car", "First Owner", "Second Owner", "Third Owner", "Fourth & Above Owner"))

# Converting the following variables to numeric
vehicle[c("mileage","engine", "max_power", "torque", "owner")] <- sapply(vehicle[c("mileage","engine", "max_power", "torque", "owner")],as.numeric)

# Omitting na values
vehicle <- na.omit(vehicle)

cat("After cleaning the dataset, we have", nrow(vehicle), "observations.")
```
## SMART Question 1: Variation of Selling Price With Respect to Different Variables

### Part1: Categorical Variables
```{r, results = 'markup'}
loadPkg("leaps")
loadPkg("car")

reg.best10 <- regsubsets(selling_price~. -name , data = vehicle, nvmax = 10, nbest = 1, method = "exhaustive")

summary(reg.best10)

plot(reg.best10, scale = "adjr2", main = "Adjusted R^2")
plot(reg.best10, scale = "bic", main = "BIC")
plot(reg.best10, scale = "Cp", main = "Cp")

cat("considering we have to maximize R2, minimize BIC and CP, and minimize the number of variables to reduce model complexity, the following model seems the best. \n")

best_model = lm(selling_price~ year+ km_driven+ seller_type+ transmission+ mileage+ max_power, data = vehicle)

summary(best_model)
```

### Part2: Numerical Variables
```{r, results = 'markup'}
data_p4 <- vehicle %>%
      	group_by(year) %>%
      	summarise(mean_sellingPrice = mean(selling_price))
p4 <- ggplot(data=data_p4, aes(x=year, y=mean_sellingPrice, group=1)) + geom_line()+ geom_point()+ scale_x_continuous(breaks = seq(1993, 2021, 2))
p4
cat("From this graph, we can see that the selling price greatly depends on the year of the model. It is higher for a more recent car than an older one. This observation is expected. \n")

data_p5 <- vehicle %>%
      	group_by(owner) %>%
	      summarise(mean_sellingPrice = mean(selling_price))
p5 <- ggplot(data=data_p5, aes(x=owner, y=mean_sellingPrice, group=1)) + geom_line()+ geom_point()
p5
cat("From this graph, we can see that the selling price greatly depends on the number of previous owners. The lesser the number of previous owner, more is the price which is expected. \n")

data_p6 <- vehicle %>%
	     group_by(seats) %>%
       summarise(mean_sellingPrice = mean(selling_price))
p6 <- ggplot(data=data_p6, aes(x=seats, y=mean_sellingPrice, group=1)) + geom_line()+ geom_point()+ scale_x_continuous(breaks = seq(0, 14, 2))
p6
cat("From this graph, we can see that the selling price depends on the number of seats, increasing till 7 for an SUV and decreasing after that. \n")

```
```{r, results = 'markup'}
ggplot(vehicle, aes(x=km_driven, y=selling_price)) + geom_point()
cat("We can see that the graph is exponential, as km_driven increases, the selling_price decreases which is expected. So to calculate the mathematical relation between these variables, we plotted them after taking log of both because we will have a linear model. \n")

plot(log10(vehicle$km_driven), log10(vehicle$selling_price))
cat("We can plot a best fit line for these variables. \n")

lin_mod <- lm(log10(vehicle$selling_price) ~ log10(vehicle$km_driven))
abline(lin_mod, col = "red")
cat("Using the coefficients we obtained from this linear model, we plotted the best fit exponential curve onto the original scatter plot.")

slope = lin_mod$coefficients[2]
intercept = lin_mod$coefficients[1]
x = vehicle$km_driven
y = (10^intercept)*x^(slope)

ggplot(vehicle)+ geom_point(aes(km_driven, selling_price), color = "yellow")+ geom_line(aes(x=km_driven, y= y, color = "exponential fit"))

```

```{r}
model = lm(selling_price~ .-name, data = vehicle)

summary(model)
cat("We can conclude that all except fuel type and owner are highly significant variables. \n")
```

## SMART Question 2: Type of car that has been sold the most (in each category) and the preferred category in each variable

